title: 'Bootstrap Theme Editor'
author: 'Thomas Coleman'
email: 'tom@ilikeprograms.com'
github:
  username: 'ilikeprograms'
  repo:     'BootstrapThemeEditor'

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
gems:        []
timezone:    nil
encoding:    nil

#future:      true
#show_drafts: false
#limit_posts: nil
#highlighter: pygments
#
#relative_permalinks: true
#
#permalink:     date
#paginate_path: 'page:num'
#paginate:      nil
#
#markdown:      kramdown
#markdown_ext:  markdown,mkdown,mkdn,mkd,md
#textile_ext:   textile
#
#excerpt_separator: "\n\n"
#
#safe:        false
#watch:       false    # deprecated
#server:      false    # deprecated
#host:        0.0.0.0
#port:        4000
#baseurl:     ""
#lsi:         false